env:
    global:
        - CC_TEST_REPORTER_ID=810f1d89cc17415a9d23357c8e123290516e177ae3f71f1b5b996c846d52d22d
language: python
matrix:
    include:
        - python: 3.8
          dist: bionic
          sudo: true
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.6
          dist: xenial
          sudo: true
        - python: 3.5
          dist: xenial
          sudo: true

before_install:
    - export POETRY_HOME=~/poetry
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - export PATH=~/poetry:$PATH
    - poetry --version

install:
    - poetry install -v

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - tox
after_script:
    - echo "$TRAVIS_PULL_REQUEST"
    - echo "$TRAVIS_PYTHON_VERSION"
    - find . -name ".coverage"
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT tests/coverage.xml; fi
